import { NextResponse } from 'next/server'
import { OAuth2Client } from 'google-auth-library'
import { prisma } from '@/lib/prisma'
import { createSession } from '@/lib/session'

export const dynamic = 'force-dynamic'

// Client ID for the mobile app (can be same or different, usually needs the web client ID for verification of idToken if generated by standard flow, or specific mobile client ID)
// For verifyIdToken, we generally check against the Client ID that *issued* the token.
// In Expo Google Auth (using standard web flow), the audience is often the Web Client ID.
// If using native android/ios client IDs, we might need to check against those.
export async function POST(req: Request) {
    try {
        const CLIENT_ID = process.env.GOOGLE_CLIENT_ID
        
        if (!CLIENT_ID) {
            console.error('Mobile Google Auth Error: GOOGLE_CLIENT_ID env var is missing or empty.')
            return NextResponse.json({ error: 'Server configuration error' }, { status: 500 })
        }

        const client = new OAuth2Client(CLIENT_ID)

        const body = await req.json()
        const { idToken } = body

        if (!idToken) {
            return NextResponse.json({ error: 'Missing idToken' }, { status: 400 })
        }

        // Verify the token
        const ticket = await client.verifyIdToken({
            idToken,
            audience: CLIENT_ID, // Use the client ID that the mobile app used to sign in
        })
        const payload = ticket.getPayload()

        if (!payload || !payload.email) {
            return NextResponse.json({ error: 'Invalid token payload' }, { status: 401 })
        }

        if (!payload.email_verified) {
             return NextResponse.json({ error: 'Email not verified' }, { status: 401 })
        }

        const email = payload.email
        const name = payload.name || email.split('@')[0]

        // Find or create user
        let user = await prisma.user.findUnique({ where: { email } })

        if (!user) {
            user = await prisma.user.create({
                data: {
                    email,
                    name,
                    role: 'USER', // Default role
                }
            })
        }

        // Create session
        const token = await createSession(user.id, user.role as 'USER' | 'VENDOR' | 'ADMIN')

        return NextResponse.json({
            ok: true,
            token,
            user: { id: user.id, email: user.email, name: user.name, role: user.role }
        })

    } catch (error) {
        // Secure logging: Avoid leaking PII/Tokens in production logs
        const safeMessage = error instanceof Error ? error.message : 'Unknown error'
        
        if (process.env.NODE_ENV !== 'production') {
             console.error('Mobile Google Auth Error (Dev):', safeMessage)
        } else {
             // In production, just log the event without details that might leak
             console.error('Mobile Google Auth verification failed.')
        }

        return NextResponse.json({ error: 'Authentication failed' }, { status: 401 })
    }
}
